### ISSUE TITLE
[PRE REVIEW]: Testing the new submission system

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews-testing#2]
**Submitting author:** @agahkarakuzu (<a href="http://orcid.org/0000-0001-7283-271X">Agah Karakuzu</a>)
**Repository:** https://github.com/agahkarakuzu/template
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @pbellec
**Reviewers:** @mathieuboudreau
**Managing EiC:** Agah Karakuzu

## Status

[![status](https://neurolibre.org/papers/b17407d40bbb47b3c42fdde8bc08ff00/status.svg)](https://neurolibre.org/papers/b17407d40bbb47b3c42fdde8bc08ff00)

Status badge code:

```
HTML: <a href="https://neurolibre.org/papers/b17407d40bbb47b3c42fdde8bc08ff00"><img src="https://neurolibre.org/papers/b17407d40bbb47b3c42fdde8bc08ff00/status.svg"></a>
Markdown: [![status](https://neurolibre.org/papers/b17407d40bbb47b3c42fdde8bc08ff00/status.svg)](https://neurolibre.org/papers/b17407d40bbb47b3c42fdde8bc08ff00)
```

**Author instructions**

Thanks for submitting your paper to TEST_JOURNAL @agahkarakuzu. **Currently, there isn't a TEST_JOURNAL editor assigned** to your paper.

The AEiC suggestion for the handling editor is @agahkarakuzu.

@agahkarakuzu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/neurolibre_reviewers) have already agreed to review for TEST_JOURNAL and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The TEST_JOURNAL submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro commands

**Comment by agahkarakuzu** [comment]
@roboneuro commands

**Comment by roboneuro** [comment]
Hello @agahkarakuzu, here are the things you can ask me to do:

```

# List all available commands
@roboneuro commands

# Add to this issue's reviewers list
@roboneuro add @username as reviewer

# Remove from this issue's reviewers list
@roboneuro remove @username from reviewers

# Get a list of all editors's GitHub handles
@roboneuro list editors

# Assign a user as the editor of this submission
@roboneuro assign @username as editor

# Remove the editor assigned to this submission
@roboneuro remove editor

# Remind an author, a reviewer or the editor to return to a review after a 
# certain period of time (supported units days and weeks)
@roboneuro remind @reviewer in 2 weeks

# Check the references of the PDF for missing DOIs
@roboneuro check references

# Perform checks on the repository
@roboneuro check repository

# Adds a checklist for the reviewer using this command
@roboneuro generate my checklist

# Set a value for version
@roboneuro set v1.0.0 as version

# Set a value for branch
@roboneuro set neurolibre-paper as branch

# Set a value for repository
@roboneuro set https://github.com/organization/repo as repository

# Set a value for the archive DOI
@roboneuro set set 10.5281/zenodo.6861996 as archive

# Mention the EiCs for the correct track
@roboneuro ping track-eic

# Reject paper
@roboneuro reject

# Withdraw paper
@roboneuro withdraw

# Invite an editor to edit a submission (sending them an email)
@roboneuro invite @(.*) as editor

# Generates the pdf paper
@roboneuro generate pdf

# Recommends the submission for acceptance
@roboneuro recommend-accept

# Accept and publish the paper
@roboneuro accept

# Update data on an accepted/published paper
@roboneuro reaccept

# Generates a LaTeX preprint file
@roboneuro generate preprint

# Flag submission with questionable scope
@roboneuro query scope

# Get a link to the complete list of reviewers
@roboneuro list reviewers

# Creates a post-review checklist with editor and authors tasks
@roboneuro create post-review checklist

# Open the review issue
@roboneuro start review

```

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by roboneuro** [comment]
:warning: [An error happened when generating the pdf](https://github.com/neurolibre/neurolibre-preprints-testing/actions/runs/4822850861?check_suite_focus=true).

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/neurolibre/neurolibre-preprints-testing/test_journal.00002/test_journal.00002/10.55458.test_journal.00002.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/neurolibre/neurolibre-preprints-testing/blob/test_journal.00002/test_journal.00002/10.55458.test_journal.00002.pdf) :page_facing_up: :point_left:

**Comment by agahkarakuzu** [comment]
@roboneuro list editors

**Comment by roboneuro** [comment]
List of NeuroLibre editors

```
@agahkarakuzu
@emdupre
@jbpoline
@ltetrel
@mathieuboudreau
@pbellec
```

**Comment by agahkarakuzu** [comment]
@roboneuro assign @mathieuboudreau  as editor

**Comment by roboneuro** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@roboneuro commands`

**Comment by agahkarakuzu** [comment]
@roboneuro add @mathieuboudreau as reviewer

**Comment by roboneuro** [comment]
Can't add reviewers: There is no editor assigned yet

**Comment by agahkarakuzu** [comment]
@roboneuro assign @pbellec as editor

**Comment by roboneuro** [comment]
Assigned! @pbellec is now the editor

**Comment by agahkarakuzu** [comment]
@roboneuro add @mathieuboudreau as reviewer

**Comment by roboneuro** [comment]
@mathieuboudreau added to the reviewers list!

**Comment by agahkarakuzu** [comment]
@roboneuro start review
